site_name: Software Guide - Mkdocs
theme:
  name: material
  features:
    - navigation.sections  # Enables sections for nested navigation
    - navigation.expand   # Expands navigation by default
    - toc.follow
    - toc.integrate
  
  # Add the 'edit' feature
  palette:
    primary: indigo
    accent: indigo
  
  # Configure the 'edit' button
  extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/your-org/your-repo
    repo_url: https://github.com/your-org/your-repo
    repo_name: your-org/your-repo
    repo_icon: fontawesome/brands/github
  
nav:
  - Home: index.md
  - Software Project Overview: overview.md
  - Installation: installation.md
  - How to Use the Software:
      - Introduction: usage/index.md
      - Create a Project: usage/create-project.md
      - Create a Process: usage/create-process.md
      - Test the Project: usage/test-project.md

plugins:
  - search
markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  version:
    provider: mike
    default: latest
    permalink: true
   
