site_name: Software Guide - Mkdocs

repo_url: https://github.com/lenadoc/SoftwareGuideMkdocs
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.sections  # Enables sections for nested navigation
    - toc.follow
    - content.action.edit  # Add this line to enable page-specific edit buttons
    - content.feedback
    - navigation.footer
    - navigation.indexes
  
  palette:
    primary: indigo
    accent: indigo

  extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/lenadoc/SoftwareGuideMkdocs
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  
nav:
  - Home: index.md
  - Software Project Overview: overview.md
  - Installation: installation.md
  - "How to Use the Software":
      - Introduction: usage/index.md
      - Create a Project: usage/create-project.md
      - Create a Process: usage/create-process.md
      - Test a Project: usage/test-project.md
plugins:
  - search
  - pdf-export:
      combined: true

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg