nname: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this to match your default branch where PRs are merged

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x  # Specify the Python version you need

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install mike

    - name: Deploy documentation
      run: |
        mike deploy 4.16 latest --branch gh-pages --push
        mike set-default 4.16 --branch gh-pages --push
