name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this to match your default branch where PRs are merged

jobs:
  deploy:
    runs-on: ubuntu-ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x  # Specify the Python version you need

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install mkdocs mike

    - name: Deploy documentation
      run: |
        mike deploy 4.16 latest --branch gh-pages --push
        mike set-default 4.16 --branch gh-pages --push
