name: Check for 404 Links

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
          pip install mkdocs
          
      - name: Build MkDocs site
        run: mkdocs build
        
      - name: Install link checker
        run: npm install -g broken-link-checker
        
      - name: Start Python HTTP server
        run: |
          python -m http.server 8000 --directory site &
          sleep 5
          
      - name: Check for broken links
        run: |
          # Run link checker and save output
          blc http://localhost:8000 -ro --exclude external > link_check.txt
          
          if grep -q "BROKEN" link_check.txt; then
            echo "::error::Found broken links in documentation:"
            echo ""
            # Get the current page being checked
            current_page=""
            while IFS= read -r line; do
              if [[ $line == "Getting links from:"* ]]; then
                current_page=$line
              elif [[ $line == *"BROKEN"* ]]; then
                echo "$current_page"
                echo "$line"
                echo "---"
              fi
            done < link_check.txt
            exit 1
          else
            echo "✅ No broken links found!"
          fi
        
      - name: Upload link check results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: link-check-results
          path: link_check.txt